# Generated by Django 2.2 on 2020-03-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['created'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.RemoveField(
            model_name='registro',
            name='message',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='updated',
        ),
        migrations.AddField(
            model_name='registro',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='registro',
            name='intencidadPico',
            field=models.CharField(max_length=10, null=True, verbose_name='IntencidadPico'),
        ),
        migrations.AddField(
            model_name='registro',
            name='irms',
            field=models.CharField(max_length=10, null=True, verbose_name='Irms'),
        ),
        migrations.AddField(
            model_name='registro',
            name='voltaje',
            field=models.CharField(max_length=10, null=True, verbose_name='Voltaje'),
        ),
        migrations.AddField(
            model_name='registro',
            name='watts',
            field=models.CharField(max_length=10, null=True, verbose_name='Watts'),
        ),
    ]
