# Generated by Django 2.2 on 2020-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMinuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irms', models.CharField(max_length=10, null=True, verbose_name='Irms')),
                ('voltaje', models.CharField(max_length=10, null=True, verbose_name='Voltaje')),
                ('watts', models.CharField(max_length=10, null=True, verbose_name='Watts')),
                ('intencidadPico', models.CharField(max_length=10, null=True, verbose_name='IntencidadPico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'RegistroMinuto',
                'verbose_name_plural': 'RegistrosMinuto',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
