# Generated by Django 2.2 on 2020-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_autonomoconfig_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrominuto',
            name='reposo',
            field=models.BooleanField(default=False, verbose_name='En reposo'),
        ),
    ]
