# Generated by Django 2.2 on 2020-05-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registrominuto_reposo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonomoconfig',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='registrominuto',
            name='reposo',
        ),
    ]
