# Generated by Django 2.2 on 2020-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200415_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrominuto',
            name='created',
            field=models.CharField(max_length=30, verbose_name='Fecha de creación'),
        ),
    ]
