# Generated by Django 2.2 on 2020-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200415_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrominuto',
            options={'ordering': ['-fecha'], 'verbose_name': 'RegistroMinuto', 'verbose_name_plural': 'RegistrosMinuto'},
        ),
        migrations.RemoveField(
            model_name='registrominuto',
            name='created',
        ),
        migrations.AddField(
            model_name='registrominuto',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='registrominuto',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Hora de creación'),
        ),
    ]
