# Generated by Django 2.2 on 2020-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200415_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.IntegerField(verbose_name='Hora de inicio')),
                ('horaFin', models.IntegerField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Configuracion del la Autonomia',
            },
        ),
    ]
