# Generated by Django 2.2 on 2020-06-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200507_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrominuto',
            name='intencidadPico',
        ),
        migrations.RemoveField(
            model_name='registrominuto',
            name='irms',
        ),
        migrations.RemoveField(
            model_name='registrominuto',
            name='voltaje',
        ),
    ]
